apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: spring-github-jenkins-2611
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-github-jenkins-2611 
  name: spring-github-jenkins-2611
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: spring-github-jenkins-2611 
